Les_2
Khaitsev/JS pull request #2
Opened 2020-11-03 10:31 UTC by Khaitsev

2020-11-04 15:42 UTC, Om1X requested changes

2020-11-04 15:42 UTC, Om1X commented on tasks/Les_2/Les_2.Task_1.js
> +a = Math.floor(Math.random()*15);
забыли var / let / const

2020-11-04 15:42 UTC, Om1X commented on tasks/Les_2/Les_2.Task_1.js
> +b = -10;
забыли var / let / const

2020-11-04 15:42 UTC, Om1X commented on tasks/Les_2/Les_2.Task_1.js
> +}
интересный вариант решения

2020-11-04 15:42 UTC, Om1X commented on tasks/Les_2/Les_2.Task_1.js
> +z = 0
и снова забыли про правильное объявление переменных.

2020-11-04 15:42 UTC, Om1X commented on tasks/Les_2/Les_2.Task_1.js
> +    return power(val,pow-1);
несколько перемудрили с условиями.

2020-11-05 08:57 UTC, Khaitsev commented
д

2020-11-05 08:57 UTC, merged